print('What is your name?')
first_name = input()
print('What is your last name?')
last_name = input()
print('What is you DOB (dd/mm/yyyy)?')
dob = input()
print('Enter a funny fact about yourself..')
fact = input()

print()
print('Your name is',first_name, last_name)
print('........................,............')
print('You was born on',dob)
print('........................,............')
print('A funny fact about you is:',fact)